### ISSUE TITLE
Limited to One Playlist

### ISSUE THREAD

**Issue by Gekocaretaker** [CodeDotJS/youtube-playlist#17] opened 2020-09-01 01:23 UTC
If I try to use this module for multiple playlist, it causes an error. I even tried calling the module in 2 different const, but it just causes the same issues.

**Comment by CodeDotJS** [comment] 2020-09-01 11:01
How you're doing it? Please paste the code here.

**Comment by Gekocaretaker** [comment] 2020-09-02 00:15
This is the file. I am using it for discord js.
https://github.com/Gekocaretaker/Lizz-AI/blob/master/commands/video.js

**Comment by CodeDotJS** [comment] 2020-09-04 14:55
All the problems are related to scope. Please have a look [here](https://scotch.io/tutorials/understanding-scope-in-javascript)

For example - 

In order to fetch contents from two playlist, you've to do - 

```js
const ytlist = require('youtube-playlist');

ytlist(urlOne, 'url').then(urlOneContent => {
  ytlist(urlTwo, 'url').then(urlTwoContent => {
    const urlOneData = urlOneContent.data.playlist;
    const urlTwoData = urlTwoContent.data.playlist;
    // do something with the available data
  });
});
```

In your code, you're doing -

```js
moronsPlaylist(moronsUrl, 'url').then(res => {
  ranYtVid = res.data.playlist;
});

solidslicerPlaylist(solidslicerUrl, 'url').then(res => {
  ranYtVid2 = res.data.playlist;
});
```

You've trying to access `ranYtVid` and `ranYtVid2` inside -

```js
if(args[0] === '107Morons') { }
```

You'll end up getting `reference error`.

Hope this helps.

**Comment by Gekocaretaker** [comment] 2020-09-04 18:25
It works perfectly. But now I am getting this error: "Cannot read property 'send' of undefined at /app/commands/video.js:32:19"
And I don't know what is wrong.

**Comment by CodeDotJS** [comment] 2020-09-04 19:16
The problem is not related to this module, so I'm closing the issue. Will be happy to clear the doubts though.

Also, try to debug the code - use `console.log(message.channel)` to see what you're getting [here](https://github.com/Gekocaretaker/Lizz-AI/blob/master/commands/video.js#L32).

**Closed as completed by CodeDotJS** 2020-09-04 19:16 UTC
